### ISSUE TITLE
Reading Star from XML

### ISSUE THREAD

**Issue by chthonic7** [CS-196-Space-Colonization/Game#15]
DOM in Filer does not recognize Star node in XML file even though Planet is recognized and throws NullPointer Exception

**Comment by chthonic7** [comment]
Apparently Document\* doesn't like 'star' so 'Star' works.

**Comment by DrOctagonopus** [comment]
Okay so when I run the game now it gives me an LWJGL exception,

SEVERE: Uncaught exception thrown in Thread[LWJGL Renderer Thread,6,main]
java.lang.NoSuchMethodError: com.thecolony.tractus.graphics.drawableobjects.DrawableObject3d.<init>(Ljava/lang/String;Lcom/jme3/scene/Node;Lcom/jme3/scene/Spatial;Lcom/jme3/math/Vector3f;)V
    at com.thecolony.tractus.worldgen.SpatialEntities.VisualEntity.initialize(VisualEntity.java:46)
    at com.thecolony.tractus.worldgen.SpatialEntities.VisualEntity.<init>(VisualEntity.java:42)
    at com.thecolony.tractus.worldgen.SpatialEntities.Planet.<init>(Planet.java:26)
    at com.thecolony.tractus.worldgen.Generator.loadPlanet(Generator.java:180)
    at com.thecolony.tractus.worldgen.Generator.loadTerritories(Generator.java:34)
    at com.thecolony.tractus.game.GameLoader.loadGame(GameLoader.java:86)
    at com.thecolony.tractus.game.Game.simpleInitApp(Game.java:112)
    at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:226)
    at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
    at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:207)
    at java.lang.Thread.run(Thread.java:744)

What's going on
